[project]
name = "querypipz"
version = "0.1.5"
description = "提供构建与使用知识库的能力"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=25.1.0",
    "llama-index-readers-github>=0.6.1",
    "toolsz>=0.1.4",
]

[tool.uv.workspace]
members = ["~/GitHub/commender"]
